### ISSUE TITLE
API key fails to connect to Superstaq

### ISSUE THREAD

**Issue by rockingcubes** [SupertechLabs/qiskit-superstaq#110]
When I try to execute the circuit on Superstaq at pulse level it fails to request using the API key.

`provider = SuperstaQProvider(api_key="MY API KEY")`
`from qiskit import *`
`qc = QuantumCircuit.from_qasm_file("qasm_file.qasm")`
`qc.draw(output='mpl')`
`out = provider.ibmq_compile(qc, target="ibmq_bogota_qpu")`
`out.circuits.draw()`

Error : `SuperstaQException: Status code: 502, Message: 'Non-retriable error making request to SuperstaQ API, Bad Gateway'`

**Comment by singular-value** [comment]
@rockingcubes do you have an API key? Feel free to email us at info@super.tech if you are interested.

**Comment by vtomole** [comment]
Hey @rockingcubes, You may obtain an API key by visiting https://superstaq.super.tech/ and signing in with a Google connected account.

**Comment by rockingcubes** [comment]
@singular-value and @vtomole I have my API key. I signed in with my gmail. I have amount in my credential as well.

**Comment by vtomole** [comment]
@rockingcubes Awesome! Does `ibmq_compile` work for you now?

**Comment by rockingcubes** [comment]
@vtomole No, when I try to execute `provider.ibmq_compile(qc, target="ibmq_bogota_qpu")` it fails and gives the above mentioned error.

**Comment by vtomole** [comment]
@vtomole Did you paste your API key to `provider = SuperstaQProvider(api_key="MY API KEY")`? (replace `MY API KEY` with the key that you got from https://superstaq.super.tech/)

**Comment by rockingcubes** [comment]
@vtomole Yes I did replace `MY API KEY`. After trying all possible ways, I posted an issue here.

**Comment by vtomole** [comment]
When was the last time you tried running that program?

**Comment by rockingcubes** [comment]
Even I tried it now but I have the same problem.

**Comment by dowusu-antwi** [comment]
Hi @rockingcubes, using the provider's `ibmq_set_token` method to update your IBM token should fix this error:
![set-ibmq](https://user-images.githubusercontent.com/18367737/155385626-88ac3cab-a106-4ec0-a969-d2c0e4721eb8.png)

**Comment by rockingcubes** [comment]
@vtomole The provide to cell 6 should be from Superstaq and not from qiskit right?

**Comment by dowusu-antwi** [comment]
> @vtomole The provide to cell 6 should be from Superstaq and not from qiskit right?

Yes, this is using the SuperstaQ provider instance.

**Comment by rockingcubes** [comment]
@vtomole I still have the same issue.

**Comment by dowusu-antwi** [comment]
Hi @rockingcubes, feel free to email me at david@super.tech so we can figure out this issue over Zoom. Thanks!

**Comment by vtomole** [comment]
Hi @rockingcubes. It has recently come to our attention that this is a bug on our end. If you don't mind, please send us the circuit that you intended to pass to `ibmq_compile`.

**Comment by rockingcubes** [comment]
Hi @vtomole , I wanted to try 3 qubit Toffoli circuit.

**Comment by vtomole** [comment]
Please paste the circuit you're trying to execute. It will be easier for me to reproduce the error.

**Comment by rockingcubes** [comment]
Here is the circuit

`OPENQASM 2.0;
include "qelib1.inc";
qreg qubits[3];
creg c[3];
x qubits[0];
x qubits[1];
ccx qubits[0],qubits[1],qubits[2];
measure qubits -> c;
`

**Comment by vtomole** [comment]
Your circuit runs fine for me. Can you please try it again?

```python
import numpy as np
import qiskit

from qiskit_superstaq.custom_gates import AceCR
from qiskit_superstaq.superstaq_provider import SuperstaQProvider

provider = SuperstaQProvider(api_key="api_key")

qc = qiskit.QuantumCircuit(3, 3)
qc.x(0)
qc.x(1)
qc.ccx(0, 1, 2)
qc.measure([0, 1, 2], [0, 1, 2])
out = provider.ibmq_compile(qc, target="ibmq_bogota_qpu")
out.draw()
```
![index](https://user-images.githubusercontent.com/8405160/156057125-8ed6dd20-a59f-4c36-9e81-c81f03621a48.png)

**Comment by rockingcubes** [comment]
It works now @vtomole. Thank you for helping me.

**Comment by vtomole** [comment]
@rockingcubes You are very welcome! Please don't hesitate to open other issues if you encounter any problems whatsoever.
