### ISSUE TITLE
Allow a user to pass in IBM specific data when creating the provider

### ISSUE THREAD

**Issue by teaguetomesh** [SupertechLabs/qiskit-superstaq#12]
Similar to `cirq_superstaq.Service.__init__()`. [Link](https://github.com/SupertechLabs/cirq-superstaq/blob/3195da8859d2068e2a43a1abdedfeb47de273c0e/cirq_superstaq/service.py#L24)

**Comment by stephanielee9** [comment]
No longer relevant because css no longer has IBM specific args
