### ISSUE TITLE
Use format.py script

### ISSUE THREAD

**Issue by singular-value** [SupertechLabs/qiskit-superstaq#140]
and other .py scripts? @perlinm?
Also for our other open source repos

**Comment by perlinm** [comment]
Maybe the correct thing to do here is to use a [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules)?

**Comment by perlinm** [comment]
Proposal: we make a new public repo inside [SupertechLabs](https://github.com/SupertechLabs) ("SupercheQ"?), throw the check scripts into there, and then make that repo a git submodule inside all `*superstaq` repos.

Soliciting thoughts from @singular-value @vtomole @richrines1 @dowusu-antwi

**Comment by richrines1** [comment]
strong agree, except i feel like it has to be `checks-superstaq`

**Comment by perlinm** [comment]
> i feel like it has to be `checks-superstaq`

Excellent name choice.  Last question before I make the repo: what license should I attach to it?  I guess Apache 2.0 since that's what's in the other `*-superstaq` repos?

**Comment by vtomole** [comment]
> Maybe the correct thing to do here is to use a [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules)

We've had so much pain dealing with git submodules in the past. Let's put this code in applications-superstaq so we can take advantage of the pypi package.

To do this "right" i think this might require more effort that we want right now. I'm pretty sure

**Comment by perlinm** [comment]
@vtomole then we might have to do some learning for how to properly use submodules, since this seems to be the correct tool for what we need here.  Maybe I can add the check scripts to the `*-superstaq` repos tentatively, but long-term we should not have to manually sync check script versions.

**Comment by vtomole** [comment]
We do know how to properly use submodules, but they make peoples' workflows not simple. Imagine onboarding interns who only know basic git and trying to get them familiar with submodules. 

I see all repos having a `format.py` script, but it's only one line that imports the format script in `applications-superstaq`. This is how we use `applications-superstaq` for our services in qiskit-superstaq` and `cirq-superstaq`.
