### ISSUE TITLE
Multiple Circuit Submission broken by change to SuperstaQ server

### ISSUE THREAD

**Issue by rohansk1** [SupertechLabs/qiskit-superstaq#16]
Specifically, an error is being thrown here in `superstaq_backend.py`:

`if "ids" not in response:
       raise Exception`

**Comment by singular-value** [comment]
This is fixed (https://github.com/SupertechLabs/qiskit-superstaq/blob/main/qiskit_superstaq/superstaq_backend.py#L133) but you'll have to upgrade qiskit-superstaq
