### ISSUE TITLE
Add `data` key `qiskit.result.Result.from_dict` call

### ISSUE THREAD

**Issue by vtomole** [SupertechLabs/qiskit-superstaq#173]
We need to return all data besides counts similar to `cirq.Result`
Line where this needs to be done: https://github.com/SupertechLabs/qiskit-superstaq/blob/65631f7c426f7f949cb7a35e8708a4b83f331424/qiskit_superstaq/superstaq_job.py#L95

**Comment by stephanielee9** [comment]
Not relevant anymore
