### ISSUE TITLE
`qss` serilazer decoding error

### ISSUE THREAD

**Issue by dowusu-antwi** [SupertechLabs/qiskit-superstaq#178]
![serializer-problem](https://user-images.githubusercontent.com/18367737/173910014-09bd4c84-01a6-47bc-b873-5e8683945780.png)

**Comment by richrines1** [comment]
@dowusu-antwi sorry i missed this before - were you ever able to get it working? if not, what version of qiskit are you using?

**Comment by dowusu-antwi** [comment]
Just checked now and it works, although with `ibmq_jakarta_qpu`, since `bogota` is retired now. I recently updated my `venv` a few days ago, so it was probably just out of date (my current `venv` has `qiskit` version `0.36.2`).
