### ISSUE TITLE
Add `SUPERSTAQ_API_KEY` environment variable

### ISSUE THREAD

**Issue by rohansk1** [SupertechLabs/qiskit-superstaq#23]
cirq-superstaq uses the `SUPERSTAQ_API_KEY` environment variable (if set), while
qiskit-superstaq does not. We should use it. That way, testing qiskit-superstaq locally does not require passing in a token directly. Proposed by @singular-value.

**Comment by vtomole** [comment]
Done: https://github.com/SupertechLabs/qiskit-superstaq/blob/57b9ba7c92f2e491b8238f67dbd60cefc4e138c7/qiskit_superstaq/superstaq_provider.py#L76
