### ISSUE TITLE
Add `jupyter notebook` docs for using `qiskit-superstaq`

### ISSUE THREAD

**Issue by dowusu-antwi** [SupertechLabs/qiskit-superstaq#48]
Need docs for accessing `qiskit-superstaq` / an example tutorial for creating and submitting a circuit through `qiskit-superstaq`.

**Comment by stephanielee9** [comment]
Not a notebook but accomplished via https://github.com/SupertechLabs/qiskit-superstaq/blob/main/examples/hello_qiskit_superstaq.py
