### ISSUE TITLE
Add documentation for developer to suppress InsecureRequestWarnings

### ISSUE THREAD

**Issue by rohansk1** [SupertechLabs/qiskit-superstaq#6]
(Migrating issue from SuperstaQ)

```
InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
```

Likely to do with the need to set `verify = False` somewhere.

**Comment by rohansk1** [comment]
(Does this only occur when doing internal testing?)

**Comment by vtomole** [comment]
> Does this only occur when doing internal testing

Yes,  adding

`verify=bool(self._backend.url == qss.API_URL)` to

https://github.com/SupertechLabs/qiskit-superstaq/blob/4242495bd111e2a3ad718545abef8089198fea27/qiskit_superstaq/superstaq_job.py#L124

Will fix this.

**Comment by rohansk1** [comment]
> > Does this only occur when doing internal testing
> 
> Yes, adding
> 
> `verify=bool(self._backend.url == qss.API_URL)` to
> 
> https://github.com/SupertechLabs/qiskit-superstaq/blob/4242495bd111e2a3ad718545abef8089198fea27/qiskit_superstaq/superstaq_job.py#L124
> 
> Will fix this.

@vtomole On the main branch, I see that `verify=bool(self._backend.url == qss.API_URL)` already exists: 

https://github.com/SupertechLabs/qiskit-superstaq/blob/d3eb2d44cd74acac3da1847c4626b5901265ef4a/qiskit_superstaq/superstaq_job.py#L125

Yet I still get these errors.

**Comment by vtomole** [comment]
Okay. Print `self._backend.url` and `qss.API_URL` before those calls when running locally and confirm that they are indeed different.

**Comment by rohansk1** [comment]
@vtomole They are different. `self_backend.url` prints as https://127.0.0.1:5000 and `qss.API_URL` prints as https://superstaq.super.tech, as expected.

**Comment by rohansk1** [comment]
Grepping for `requests.get` and `requests.post` in the codebase shows that wherever we call each one, we already make sure to set `verify=bool(self._backend.url == qss.API_URL)`, which is why I'm confused about this.

**Comment by rohansk1** [comment]
After conversation with @vtomole, the agreed solution is to add documentation suggesting that the developer run `export PYTHONWARNINGS="ignore:Unverified HTTPS request"` in `qiskit-superstaq/examples` to suppress the InsecureRequestWarnings. These warnings won't show up for the user because the certificate for superstaq.super.tech is valid, whereas while testing we use https://127.0.0.1:5000

**Comment by singular-value** [comment]
This was taken care of. No more warnings appear from prod server b/c of the verify kwarg.
